### ISSUE TITLE
Unhandled Bad Gateway during sign in

### ISSUE THREAD

**Issue by JonasWanke** [schul-cloud/schulcloud-flutter#210]
App version: 9beb4fe

The following error occurrs during sign in but isn't displayed in the app:
```
I/flutter (30603): 💡  10:48:51.407: "Logging in as demo-lehrer@schul-cloud.org…"
D/ViewRootImpl@bca0122[MainActivity](30603): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(30603): prepareNavigationBarInfo() DecorView@cd7fd1f[MainActivity]
D/InputMethodManager(30603): getNavigationBarColor() -855310
D/ViewRootImpl@bca0122[MainActivity](30603): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(30603): prepareNavigationBarInfo() DecorView@cd7fd1f[MainActivity]
D/InputMethodManager(30603): getNavigationBarColor() -855310
E/flutter (30603): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: FormatException: Unexpected character (at character 1)
E/flutter (30603): <html><body><h1>502 Bad Gateway</h1>
E/flutter (30603): ^
E/flutter (30603):
E/flutter (30603): #0      _ChunkedJsonParser.fail  (dart:convert-patch/convert_patch.dart:1394:5)
E/flutter (30603): #1      _ChunkedJsonParser.parseNumber  (dart:convert-patch/convert_patch.dart:1261:9)
E/flutter (30603): #2      _ChunkedJsonParser.parse  (dart:convert-patch/convert_patch.dart:926:22)
E/flutter (30603): #3      _parseJson  (dart:convert-patch/convert_patch.dart:31:10)
E/flutter (30603): #4      JsonDecoder.convert  (dart:convert/json.dart:495:36)
E/flutter (30603): #5      JsonCodec.decode  (dart:convert/json.dart:153:41)
E/flutter (30603): #6      NetworkService._makeCall 
package:schulcloud/…/services/network.dart:169
E/flutter (30603): <asynchronous suspension>
E/flutter (30603): #7      NetworkService.post 
package:schulcloud/…/services/network.dart:121
E/flutter (30603): #8      LoginBloc.login 
package:schulcloud/login/bloc.dart:38
E/flutter (30603): <asynchronous suspension>
E/flutter (30603): #9      LoginBloc.loginAsDemoTeacher 
package:schulcloud/login/bloc.dart:56
E/flutter (30603): #10     _LoginFormState._loginAsDemoTeacher.<anonymous closure> 
package:schulcloud/…/widgets/form.dart:63
E/flutter (30603): #11     _LoginFormState._executeLogin 
package:schulcloud/…/widgets/form.dart:29
E/flutter (30603): #12     _LoginFormState._loginAsDemoTeacher 
package:schulcloud/…/widgets/form.dart:63
E/flutter (30603): #13     _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:706
E/flutter (30603): #14     _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:789
E/flutter (30603): #15     GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:182
E/flutter (30603): #16     TapGestureRecognizer.handleTapUp 
package:flutter/…/gestures/tap.dart:486
E/flutter (30603): #17     BaseTapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:264
E/flutter (30603): #18     BaseTapGestureRecognizer.acceptGesture 
package:flutter/…/gestures/tap.dart:236
E/flutter (30603): #19     GestureArenaManager.sweep 
package:flutter/…/gestures/arena.dart:156
E/flutter (30603): #20     GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:222
E/flutter (30603): #21     GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:198
E/flutter (30603): #22     GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:156
E/flutter (30603): #23     GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:102
E/flutter (30603): #24     GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:86
E/flutter (30603): #25     _rootRunUnary  (dart:async/zone.dart:1138:13)
E/flutter (30603): #26     _CustomZone.runUnary  (dart:async/zone.dart:1031:19)
E/flutter (30603): #27     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:933:7)
E/flutter (30603): #28     _invoke1  (dart:ui/hooks.dart:273:10)
E/flutter (30603): #29     _dispatchPointerDataPacket  (dart:ui/hooks.dart:182:5)
E/flutter (30603):
```

**Comment by JonasWanke** [comment]
Signing in now uses a WebView (#190) and Bad Gateway will be caught in #223
